In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [2]:
df_2023v12 = pd.read_excel('../data/raw/2023-v12-04092024-EU MRV Publication of information.xlsx', header=2)
# df_2022v219 = pd.read_excel('../data/raw/2022-v219-07082024-EU MRV Publication of information.xlsx', header=2)
# df_2021v209 = pd.read_excel('../data/raw/2021-v209-27062024-EU MRV Publication of information.xlsx', header=2)
# df_2020v198 = pd.read_excel('../data/raw/2020-v198-07062024-EU MRV Publication of information.xlsx', header=2)
# df_2019v223 = pd.read_excel('../data/raw/2019-v223-28082024-EU MRV Publication of information.xlsx', header=2)
# df_2018v271 = pd.read_excel('../data/raw/2018-v271-14052024-EU MRV Publication of information.xlsx', header=2)

/Users/vasileiosvyzas/miniconda3/envs/carbonchain_env/lib/python3.9/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [3]:
df_2023v12.shape

(12398, 62)

In [3]:
df_2023v12.head()

,IMO Number,Name,Ship type,Reporting Period,Technical efficiency,Port of Registry,Home Port,Ice Class,DoC issue date,DoC expiry date,Verifier Number,Verifier Name,Verifier NAB,Verifier Address,Verifier City,Verifier Accreditation number,Verifier Country,A,B,C,D,D.1,Total fuel consumption [m tonnes],Fuel consumptions assigned to On laden [m tonnes],Total CO₂ emissions [m tonnes],CO₂ emissions from all voyages between ports under a MS jurisdiction [m tonnes],CO₂ emissions from all voyages which departed from ports under a MS jurisdiction [m tonnes],CO₂ emissions from all voyages to ports under a MS jurisdiction [m tonnes],CO₂ emissions which occurred within ports under a MS jurisdiction at berth [m tonnes],CO₂ emissions assigned to Passenger transport [m tonnes],CO₂ emissions assigned to Freight transport [m tonnes],CO₂ emissions assigned to On laden [m tonnes],Annual Time spent at sea [hours],Annual average Fuel consumption per distance [kg / n mile],Annual average Fuel consumption per transport work (mass) [g / m tonnes · n miles],Annual average Fuel consumption per transport work (volume) [g / m³ · n miles],Annual average Fuel consumption per transport work (dwt) [g / dwt carried · n miles],Annual average Fuel consumption per transport work (pax) [g / pax · n miles],Annual average Fuel consumption per transport work (freight) [g / m tonnes · n miles],Annual average CO₂ emissions per distance [kg CO₂ / n mile],Annual average CO₂ emissions per transport work (mass) [g CO₂ / m tonnes · n miles],Annual average CO₂ emissions per transport work (volume) [g CO₂ / m³ · n miles],Annual average CO₂ emissions per transport work (dwt) [g CO₂ / dwt carried · n miles],Annual average CO₂ emissions per transport work (pax) [g CO₂ / pax · n miles],Annual average CO₂ emissions per transport work (freight) [g CO₂ / m tonnes · n miles],Through ice [n miles],Time spent at sea [hours],Total time spent at sea through ice [hours],Fuel consumption per distance on laden voyages [kg / n mile],Fuel consumption per transport work (mass) on laden voyages [g / m tonnes · n miles],Fuel consumption per transport work (volume) on laden voyages [g / m³ · n miles],Fuel consumption per transport work (dwt) on laden voyages [g / dwt carried · n miles],Fuel consumption per transport work (pax) on laden voyages [g / pax · n miles],Fuel consumption per transport work (freight) on laden voyages [g / m tonnes · n miles],CO₂ emissions per distance on laden voyages [kg CO₂ / n mile],CO₂ emissions per transport work (mass) on laden voyages [g CO₂ / m tonnes · n miles],CO₂ emissions per transport work (volume) on laden voyages [g CO₂ / m³ · n miles],CO₂ emissions per transport work (dwt) on laden voyages [g CO₂ / dwt carried · n miles],CO₂ emissions per transport work (pax) on laden voyages [g CO₂ / pax · n miles],CO₂ emissions per transport work (freight) on laden voyages [g CO₂ / m tonnes · n miles],Additional information to facilitate the understanding of the reported average operational energy efficiency indicators,Average density of the cargo transported [m tonnes / m³]
0,1007213,OCTOPUS,Other ship types,2023,EEDI (0 gCO₂/t·nm),George Town,NaN,NaN,17/05/2024,30/06/2025,581,HELLENIC LLOYD'S S.A.,HELLENIC ACCREDITATION SYSTEM,"348 Syggrou Avenue,",Athens,1190,Greece,NaN,NaN,Yes,NaN,NaN,1528.57,NaN,4900.59,1092.06,1371.40,2437.14,0.00,NaN,NaN,NaN,1343.50,116.16,1561850.02,NaN,Division by zero!,NaN,NaN,372.4,5007295.47,NaN,Division by zero!,NaN,NaN,NaN,1343.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,6602898,OCEAN MAJESTY,Passenger ship,2023,EEXI (33.5 gCO₂/t·nm),Madeira,NaN,NaN,24/07/2024,30/06/2025,NaN,Bureau Veritas Certification France,COFRAC,1 Place Zaha Hadid,92400 COURBEVOIE,3-2047 rév. 1,France,Yes,NaN,NaN,NaN,NaN,1689.05,NaN,5409.95,3095.42,994.53,806.15,513.86,NaN,NaN,NaN,1159.48,104.44,NaN,NaN,NaN,368.84,NaN,334.51,NaN,NaN,NaN,1181.37,NaN,NaN,1159.48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,7037806,IONIAN STAR,Ro-pax ship,2023,EIV (19 gCO₂/t·nm),Panama,NaN,IC,30/04/2024,30/06/2025,NaN,NORMEC VERIFAVIA SAS,COFRAC,"Tour Egée, 9-11 Allée De L'arche",Courbevoie,3-2127,France,Yes,NaN,NaN,NaN,NaN,2754.25,NaN,8830.12,7403.90,0.00,0.00,1426.22,4442.33,2961.57,NaN,2992.50,75.87,NaN,NaN,NaN,146.13,57.96,243.25,NaN,NaN,NaN,468.48,185.81,NaN,2992.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,7043843,TALOS,Ro-ro ship,2023,EIV (48.71 gCO₂/t·nm),Piraeus,Piraeus,NaN,25/06/2024,30/06/2025,NaN,EMICERT,HELLENIC ACCREDITATION SYSTEM (ESYD),"Kodrou & Filellinon str., 15232, Chalandri,",ATHENS,874-4,Greece,Yes,NaN,NaN,NaN,NaN,2450.35,NaN,7855.82,7438.43,0.00,0.00,417.39,NaN,NaN,NaN,3234.23,65.34,160.48,NaN,NaN,NaN,NaN,209.47,514.49,NaN,NaN,NaN,NaN,NaN,3234.23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,7207451,SPORADES STAR,Ro-pax ship,2023,EIV (50.15 gCO₂/t·nm),PIRAEUS,NaN,NaN,20/06/2024,30/06/2025,NaN,EMICERT,HELLENIC ACCREDITATION SYSTEM (ESYD),"Kodrou & Filellinon str., 15232, Chalandri,",ATHENS,874-4,Greece,Yes,NaN,NaN,NaN,NaN,2892.10,NaN,9217.94,9217.90,0.00,0.00,0.00,7056.33,2161.61,NaN,2158.00,96.03,NaN,NaN,NaN,673.99,1968.76,306.06,NaN,NaN,NaN,2148.2,6274.98,NaN,2158.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df_2023v12.tail()

,IMO Number,Name,Ship type,Reporting Period,Technical efficiency,Port of Registry,Home Port,Ice Class,DoC issue date,DoC expiry date,Verifier Number,Verifier Name,Verifier NAB,Verifier Address,Verifier City,Verifier Accreditation number,Verifier Country,A,B,C,D,D.1,Total fuel consumption [m tonnes],Fuel consumptions assigned to On laden [m tonnes],Total CO₂ emissions [m tonnes],CO₂ emissions from all voyages between ports under a MS jurisdiction [m tonnes],CO₂ emissions from all voyages which departed from ports under a MS jurisdiction [m tonnes],CO₂ emissions from all voyages to ports under a MS jurisdiction [m tonnes],CO₂ emissions which occurred within ports under a MS jurisdiction at berth [m tonnes],CO₂ emissions assigned to Passenger transport [m tonnes],CO₂ emissions assigned to Freight transport [m tonnes],CO₂ emissions assigned to On laden [m tonnes],Annual Time spent at sea [hours],Annual average Fuel consumption per distance [kg / n mile],Annual average Fuel consumption per transport work (mass) [g / m tonnes · n miles],Annual average Fuel consumption per transport work (volume) [g / m³ · n miles],Annual average Fuel consumption per transport work (dwt) [g / dwt carried · n miles],Annual average Fuel consumption per transport work (pax) [g / pax · n miles],Annual average Fuel consumption per transport work (freight) [g / m tonnes · n miles],Annual average CO₂ emissions per distance [kg CO₂ / n mile],Annual average CO₂ emissions per transport work (mass) [g CO₂ / m tonnes · n miles],Annual average CO₂ emissions per transport work (volume) [g CO₂ / m³ · n miles],Annual average CO₂ emissions per transport work (dwt) [g CO₂ / dwt carried · n miles],Annual average CO₂ emissions per transport work (pax) [g CO₂ / pax · n miles],Annual average CO₂ emissions per transport work (freight) [g CO₂ / m tonnes · n miles],Through ice [n miles],Time spent at sea [hours],Total time spent at sea through ice [hours],Fuel consumption per distance on laden voyages [kg / n mile],Fuel consumption per transport work (mass) on laden voyages [g / m tonnes · n miles],Fuel consumption per transport work (volume) on laden voyages [g / m³ · n miles],Fuel consumption per transport work (dwt) on laden voyages [g / dwt carried · n miles],Fuel consumption per transport work (pax) on laden voyages [g / pax · n miles],Fuel consumption per transport work (freight) on laden voyages [g / m tonnes · n miles],CO₂ emissions per distance on laden voyages [kg CO₂ / n mile],CO₂ emissions per transport work (mass) on laden voyages [g CO₂ / m tonnes · n miles],CO₂ emissions per transport work (volume) on laden voyages [g CO₂ / m³ · n miles],CO₂ emissions per transport work (dwt) on laden voyages [g CO₂ / dwt carried · n miles],CO₂ emissions per transport work (pax) on laden voyages [g CO₂ / pax · n miles],CO₂ emissions per transport work (freight) on laden voyages [g CO₂ / m tonnes · n miles],Additional information to facilitate the understanding of the reported average operational energy efficiency indicators,Average density of the cargo transported [m tonnes / m³]
12393,9976044,GREEN KEMI,General cargo ship,2023,EEDI (3.75 gCO₂/t·nm),Panama,NaN,IA,29/04/2024,30/06/2025,541,CHINA CLASSIFICATION SOCIETY,The Italian Accreditation Body (ACCREDIA),CCS Mansion 9 DONGZHIMEN NAN DA JIE,Beijing,0003VV,China,Yes,NaN,NaN,NaN,NaN,113.27,NaN,355.75,0.0,0.00,355.75,0.00,NaN,NaN,NaN,97.50,87.94,96,NaN,1.29,NaN,NaN,276.18,301.51,NaN,4.06,NaN,NaN,NaN,97.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12394,9976070,GREEN RAUMA,General cargo ship,2023,EEDI (3.77 gCO₂/t·nm),Panama,NaN,IA,29/04/2024,30/06/2025,541,CHINA CLASSIFICATION SOCIETY,The Italian Accreditation Body (ACCREDIA),CCS Mansion 9 DONGZHIMEN NAN DA JIE,Beijing,0003VV,China,Yes,NaN,NaN,NaN,NaN,183.10,NaN,570.17,0.0,0.00,570.17,0.00,NaN,NaN,NaN,207.01,81.63,1.32,NaN,1.2,NaN,NaN,254.18,4.13,NaN,3.74,NaN,NaN,NaN,207.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12395,9980356,LITTLE EMMA,Container ship,2023,EEDI (15.6 gCO₂/t·nm),Monrovia,Monrovia,NaN,11/06/2024,30/06/2025,NaN,RINA HELLAS LTD,Hellenic Accreditation System,"5, Aitolikou Street and Kastoros - 18545",Piraeus,1325,Greece,Yes,NaN,NaN,NaN,NaN,953.86,NaN,2998.44,1323.0,44.80,1248.40,382.30,NaN,NaN,NaN,961.30,76.04,11.19,NaN,NaN,NaN,NaN,239.02,35.16,NaN,NaN,NaN,NaN,NaN,961.30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12396,9985980,EVA HANSA,Chemical tanker,2023,EEDI (7.18 gCO₂/t·nm),Manila,NaN,NaN,30/04/2024,30/06/2025,NaN,Bureau Veritas Certification France,COFRAC,1 Place Zaha Hadid,92400 COURBEVOIE,3-2047 rév. 1,France,NaN,NaN,Yes,NaN,NaN,200.92,143.73,627.88,0.0,110.64,431.95,85.29,NaN,NaN,448.13,219.20,65.09,4,NaN,NaN,NaN,NaN,203.39,12.51,NaN,NaN,NaN,NaN,NaN,219.20,NaN,54.69,2.86,NaN,NaN,NaN,NaN,170.52,8.93,NaN,NaN,NaN,NaN,NaN,NaN
12397,9990167,YU AN,General cargo ship,2023,EEXI (4 gCO₂/t·nm),Hong kong,NaN,NaN,22/04/2024,30/06/2025,541,CHINA CLASSIFICATION SOCIETY,The Italian Accreditation Body (ACCREDIA),CCS Mansion 9 DONGZHIMEN NAN DA JIE,Beijing,0003VV,China,Yes,NaN,NaN,NaN,NaN,0.00,NaN,0.00,0.0,0.00,0.00,0.00,NaN,NaN,NaN,0.00,Division by zero!,Division by zero!,NaN,Division by zero!,NaN,NaN,Division by zero!,Division by zero!,NaN,Division by zero!,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df_2023v12.columns

Index(['IMO Number', 'Name', 'Ship type', 'Reporting Period',
       'Technical efficiency', 'Port of Registry', 'Home Port', 'Ice Class',
       'DoC issue date', 'DoC expiry date', 'Verifier Number', 'Verifier Name',
       'Verifier NAB', 'Verifier Address', 'Verifier City',
       'Verifier Accreditation number', 'Verifier Country', 'A', 'B', 'C', 'D',
       'D.1', 'Total fuel consumption [m tonnes]',
       'Fuel consumptions assigned to On laden [m tonnes]',
       'Total CO₂ emissions [m tonnes]',
       'CO₂ emissions from all voyages between ports under a MS jurisdiction [m tonnes]',
       'CO₂ emissions from all voyages which departed from ports under a MS jurisdiction [m tonnes]',
       'CO₂ emissions from all voyages to ports under a MS jurisdiction [m tonnes]',
       'CO₂ emissions which occurred within ports under a MS jurisdiction at berth [m tonnes]',
       'CO₂ emissions assigned to Passenger transport [m tonnes]',
       'CO₂ emissions assigned to Freight transport [m tonnes]',
       'CO₂ emissions assigned to On laden [m tonnes]',
       'Annual Time spent at sea [hours]',
       'Annual average Fuel consumption per distance [kg / n mile]',
       'Annual average Fuel consumption per transport work (mass) [g / m tonnes · n miles]',
       'Annual average Fuel consumption per transport work (volume) [g / m³ · n miles]',
       'Annual average Fuel consumption per transport work (dwt) [g / dwt carried · n miles]',
       'Annual average Fuel consumption per transport work (pax) [g / pax · n miles]',
       'Annual average Fuel consumption per transport work (freight) [g / m tonnes · n miles]',
       'Annual average CO₂ emissions per distance [kg CO₂ / n mile]',
       'Annual average CO₂ emissions per transport work (mass) [g CO₂ / m tonnes · n miles]',
       'Annual average CO₂ emissions per transport work (volume) [g CO₂ / m³ · n miles]',
       'Annual average CO₂ emissions per transport work (dwt) [g CO₂ / dwt carried · n miles]',
       'Annual average CO₂ emissions per transport work (pax) [g CO₂ / pax · n miles]',
       'Annual average CO₂ emissions per transport work (freight) [g CO₂ / m tonnes · n miles]',
       'Through ice [n miles]', 'Time spent at sea [hours]',
       'Total time spent at sea through ice [hours]',
       'Fuel consumption per distance on laden voyages [kg / n mile]',
       'Fuel consumption per transport work (mass) on laden voyages [g / m tonnes · n miles]',
       'Fuel consumption per transport work (volume) on laden voyages [g / m³ · n miles]',
       'Fuel consumption per transport work (dwt) on laden voyages [g / dwt carried · n miles]',
       'Fuel consumption per transport work (pax) on laden voyages [g / pax · n miles]',
       'Fuel consumption per transport work (freight) on laden voyages [g / m tonnes · n miles]',
       'CO₂ emissions per distance on laden voyages [kg CO₂ / n mile]',
       'CO₂ emissions per transport work (mass) on laden voyages [g CO₂ / m tonnes · n miles]',
       'CO₂ emissions per transport work (volume) on laden voyages [g CO₂ / m³ · n miles]',
       'CO₂ emissions per transport work (dwt) on laden voyages [g CO₂ / dwt carried · n miles]',
       'CO₂ emissions per transport work (pax) on laden voyages [g CO₂ / pax · n miles]',
       'CO₂ emissions per transport work (freight) on laden voyages [g CO₂ / m tonnes · n miles]',
       'Additional information to facilitate the understanding of the reported average operational energy efficiency indicators',
       'Average density of the cargo transported [m tonnes / m³]'],
      dtype='object')

In [3]:
print(df_2023v12.shape )
print(df_2022v219.shape)
print(df_2021v209.shape)
print(df_2020v198.shape)
print(df_2019v223.shape)
print(df_2018v271.shape)

(12398, 62)
(13464, 62)
(12465, 62)
(12116, 62)
(12419, 62)
(12257, 62)

In [46]:
# df_2018v270['D.1'] = np.nan

## TODO: Move the D.1 column next to the columns A, B, C, D

In [ ]:
# print(df_2023v11.shape )
# print(df_2022v220.shape)
# print(df_2021v210.shape)
# print(df_2020v199.shape)
# print(df_2019v222.shape)
# print(df_2018v270.shape)

# Some columns in some dataframes are completely empty so I will be filling them in

In [4]:
df_2023v12.fillna('Missing', inplace=True)
df_2022v219.fillna('Missing', inplace=True)
df_2021v209.fillna('Missing', inplace=True)
df_2020v198.fillna('Missing', inplace=True)
df_2019v223.fillna('Missing', inplace=True)
df_2018v271.fillna('Missing', inplace=True)

In [5]:
df_2020v198['CO₂ emissions per transport work (pax) on laden voyages [g CO₂ / pax · n miles]'].isnull().value_counts()

False    12116
Name: CO₂ emissions per transport work (pax) on laden voyages [g CO₂ / pax · n miles], dtype: int64

# Drop columns that cause problems

In [7]:
def drop_verifier_address(df):
    df = df.drop(['Verifier Address', 'Additional information to facilitate the understanding of the reported average operational energy efficiency indicators'], axis=1)
    return df

In [8]:
df_2023v12 = drop_verifier_address(df_2023v12)
df_2022v219 = drop_verifier_address(df_2022v219)
df_2021v209 = drop_verifier_address(df_2021v209)
df_2020v198 = drop_verifier_address(df_2020v198)
df_2019v223 = drop_verifier_address(df_2019v223)
df_2018v271 = drop_verifier_address(df_2018v271)

In [9]:
print(df_2023v12.shape )
print(df_2022v219.shape)
print(df_2021v209.shape)
print(df_2020v198.shape)
print(df_2019v223.shape)
print(df_2018v271.shape)

(12398, 60)
(13464, 60)
(12465, 60)
(12116, 60)
(12419, 60)
(12257, 60)

# Compare dataframes if they have the same schema

In [10]:
def compare_dataframe_schemas(df1, df2):
    # Get the column names and dtypes for both DataFrames
    schema1 = pd.DataFrame({'column': df1.columns, 'dtype': df1.dtypes})
    schema2 = pd.DataFrame({'column': df2.columns, 'dtype': df2.dtypes})

    # Sort both schemas by column name for consistent comparison
    schema1 = schema1.sort_values('column').reset_index(drop=True)
    schema2 = schema2.sort_values('column').reset_index(drop=True)

    # Compare the schemas
    if schema1.equals(schema2):
        print("The schemas are identical.")
    else:
        print("The schemas are different.")
        
        # Find columns in df1 that are not in df2
        missing_in_df2 = set(df1.columns) - set(df2.columns)
        if missing_in_df2:
            print(f"Columns in df1 but not in df2: {missing_in_df2}")
        
        # Find columns in df2 that are not in df1
        missing_in_df1 = set(df2.columns) - set(df1.columns)
        if missing_in_df1:
            print(f"Columns in df2 but not in df1: {missing_in_df1}")
        
        # Compare dtypes for common columns
        common_columns = set(df1.columns) & set(df2.columns)
        for col in common_columns:
            if df1[col].dtype != df2[col].dtype:
                print(f"Column '{col}' has different dtypes: {df1[col].dtype} in df1, {df2[col].dtype} in df2")

In [11]:
compare_dataframe_schemas(df_2023v12, df_2022v219)

The schemas are identical.

In [14]:
compare_dataframe_schemas(df_2022v219, df_2019v223)

The schemas are different.
Columns in df1 but not in df2: {'Annual Time spent at sea [hours]', 'Time spent at sea [hours]'}
Columns in df2 but not in df1: {'Annual Total time spent at sea [hours]', 'Total time spent at sea [hours]'}

# Add columns and drop useless columns

In [15]:
df_2018v271.rename(columns={'Annual Total time spent at sea [hours]': 'Annual Time spent at sea [hours]', 'Total time spent at sea [hours]': 'Time spent at sea [hours]'}, inplace=True)
df_2019v223.rename(columns={'Annual Total time spent at sea [hours]': 'Annual Time spent at sea [hours]', 'Total time spent at sea [hours]': 'Time spent at sea [hours]'}, inplace=True)

In [16]:
compare_dataframe_schemas(df_2023v12, df_2019v223)

The schemas are identical.

In [17]:
compare_dataframe_schemas(df_2022v219, df_2018v271)

The schemas are identical.

In [18]:
compare_dataframe_schemas(df_2018v271, df_2019v223)

The schemas are identical.

In [19]:
def add_generation_date(df, date):
    df['Generation_date'] = date
    df['Generation_date'] = pd.to_datetime(df['Generation_date'], format='%d%m%Y')
    
    return df

In [20]:
df_2023v12 = add_generation_date(df_2023v12, '04092024')
df_2022v219 = add_generation_date(df_2022v219, '07082024')
df_2021v209 = add_generation_date(df_2021v209, '27062024')
df_2020v198 = add_generation_date(df_2020v198, '07062024')
df_2019v223 = add_generation_date(df_2019v223, '28082024')
df_2018v271 = add_generation_date(df_2018v271, '14052024')

In [21]:
print(df_2023v12.shape)
print(df_2022v219.shape)
print(df_2021v209.shape)
print(df_2020v198.shape)
print(df_2019v223.shape)
print(df_2018v271.shape)

(12398, 61)
(13464, 61)
(12465, 61)
(12116, 61)
(12419, 61)
(12257, 61)

# Write everything on disk

In [23]:
df_2023v12.to_csv('/Users/vasileiosvyzas/Downloads/2023-v12-04092024-EU MRV Publication of information.csv', index=False, lineterminator='\n')
df_2022v219.to_csv('/Users/vasileiosvyzas/Downloads/2022-v219-07082024-EU MRV Publication of information.csv', index=False, lineterminator='\n')
df_2021v209.to_csv('/Users/vasileiosvyzas/Downloads/2021-v209-27062024-EU MRV Publication of information.csv', index=False, lineterminator='\n')
df_2020v198.to_csv('/Users/vasileiosvyzas/Downloads/2020-v198-07062024-EU MRV Publication of information.csv', index=False, lineterminator='\n')
df_2020v198.to_csv('/Users/vasileiosvyzas/Downloads/2019-v223-28082024-EU MRV Publication of information.csv', index=False, lineterminator='\n')
df_2018v271.to_csv('/Users/vasileiosvyzas/Downloads/2018-v271-14052024-EU MRV Publication of information.csv', index=False, lineterminator='\n')